import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";
import { db } from "@/lib/db";
import { outputDir, fileExists } from "@/lib/paths";

export const dynamic = "force-dynamic";

/**
 * GET /api/jobs/{id}/youtube-metadata
 *
 * Returns the YouTube metadata JSON if it exists (generated by the
 * youtube_optimize.py script after render completes).
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    if (!id) {
      return NextResponse.json({ error: "Job id is required." }, { status: 400 });
    }

    const job = await db.job.findUnique({
      where: { id },
      select: { id: true, status: true, outputDir: true },
    });

    if (!job) {
      return NextResponse.json({ error: "Job not found." }, { status: 404 });
    }

    // Look for youtube_metadata.json in the job's output/youtube/ directory
    const metadataPath = path.join(outputDir(job.id), "youtube", "youtube_metadata.json");

    if (!(await fileExists(metadataPath))) {
      return NextResponse.json({
        error: "YouTube metadata not generated yet.",
        hint: job.status !== "done"
          ? "Wait for the pipeline to complete."
          : "YouTube optimization may have failed. Check job logs.",
      }, { status: 404 });
    }

    const raw = await fs.readFile(metadataPath, "utf8");
    const metadata = JSON.parse(raw);

    return NextResponse.json({ metadata });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to read YouTube metadata.", detail: String(err) },
      { status: 500 }
    );
  }
}
